apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: leonahpd/healthai-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-service:27017/health_ai"
            - name: PORT
              value: "5000"
            - name: JWT_SECRET
              value: "supersecretkey123"
            - name: HUGGINGFACE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: HUGGINGFACE_API_KEY 
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort   # ✅ ADD THIS
  selector:
    app: backend
  ports:
    - port: 5000        # internal service port
      targetPort: 5000
      nodePort: 30007   # external access
---
#apiVersion: v1
#data:
#  HUGGINGFACE_API_KEY: aGZfTEZvbU1sU0RRUkhIbGh4cllGSnJpaXRScWtaaWtscXhxcQ==
#kind: Secret
#metadata:
#  name: hf-secret
#type: Opaque
